import { Order } from './OrderCard';

const ORDERS_DATA: Order[] = [
  {
    id: '10234',
    status: 'delivered',
    placedDate: 'Sep 22, 2025',
    trackingNo: '62562616',
    items: [
      { id: '1', name: 'Brand Name\nGood Stuff Red Pipe Tobacco - 16 oz. Bag', unitPrice: 126.66, quantity: 2, image: 'https://via.placeholder.com/60x60?text=Tobacco' },
      { id: '2', name: 'Brand Name\nGood Stuff Red Pipe Tobacco - 16 oz. Bag', unitPrice: 126.66, quantity: 2, image: 'https://via.placeholder.com/60x60?text=Tobacco' },
      { id: '3', name: 'Brand Name\nGood Stuff Red Pipe Tobacco - 16 oz. Bag', unitPrice: 126.66, quantity: 2, image: 'https://via.placeholder.com/60x60?text=Tobacco' },
    ],
    tax: 5,
    discount: 5,
    shippingCost: 126.66,
    subTotal: 126.66,
    paymentAmount: 171.5,
    paid: true,
  },
  {
    id: '10235',
    status: 'processing',
    placedDate: 'Sep 23, 2025',
    trackingNo: '62562617',
    items: [
      { id: '1', name: 'Brand Name\nProduct A - 16 oz. Bag', unitPrice: 100.0, quantity: 1, image: 'https://via.placeholder.com/60x60?text=ProductA' },
      { id: '2', name: 'Brand Name\nProduct B - 16 oz. Bag', unitPrice: 150.0, quantity: 2, image: 'https://via.placeholder.com/60x60?text=ProductB' },
    ],
    tax: 5,
    discount: 5,
    shippingCost: 100.0,
    subTotal: 400.0,
    paymentAmount: 420.0,
    paid: true,
  },
  {
    id: '10236',
    status: 'shipped',
    placedDate: 'Sep 24, 2025',
    trackingNo: '62562618',
    items: [
      { id: '1', name: 'Brand Name\nProduct C - 16 oz. Bag', unitPrice: 80.0, quantity: 3, image: 'https://via.placeholder.com/60x60?text=ProductC' },
      { id: '2', name: 'Brand Name\nProduct D - 16 oz. Bag', unitPrice: 120.0, quantity: 2, image: 'https://via.placeholder.com/60x60?text=ProductD' },
    ],
    tax: 5,
    discount: 5,
    shippingCost: 80.0,
    subTotal: 360.0,
    paymentAmount: 378.0,
    paid: true,
  },
  {
    id: '10237',
    status: 'cancelled',
    placedDate: 'Sep 25, 2025',
    trackingNo: '62562619',
    items: [
      { id: '1', name: 'Brand Name\nProduct E - 16 oz. Bag', unitPrice: 95.0, quantity: 2, image: 'https://via.placeholder.com/60x60?text=ProductE' },
    ],
    tax: 5,
    discount: 5,
    shippingCost: 95.0,
    subTotal: 190.0,
    paymentAmount: 199.5,
    paid: false,
  },
  {
    id: '10238',
    status: 'delivered',
    placedDate: 'Sep 26, 2025',
    trackingNo: '62562620',
    items: [
      { id: '1', name: 'Brand Name\nProduct F - 16 oz. Bag', unitPrice: 110.0, quantity: 1, image: 'https://via.placeholder.com/60x60?text=ProductF' },
      { id: '2', name: 'Brand Name\nProduct G - 16 oz. Bag', unitPrice: 140.0, quantity: 1, image: 'https://via.placeholder.com/60x60?text=ProductG' },
      { id: '3', name: 'Brand Name\nProduct H - 16 oz. Bag', unitPrice: 130.0, quantity: 1, image: 'https://via.placeholder.com/60x60?text=ProductH' },
      { id: '4', name: 'Brand Name\nProduct I - 16 oz. Bag', unitPrice: 120.0, quantity: 1, image: 'https://via.placeholder.com/60x60?text=ProductI' },
    ],
    tax: 5,
    discount: 5,
    shippingCost: 120.0,
    subTotal: 500.0,
    paymentAmount: 525.0,
    paid: true,
  },
  {
    id: '10239',
    status: 'processing',
    placedDate: 'Sep 27, 2025',
    trackingNo: '62562621',
    items: [
      { id: '1', name: 'Brand Name\nProduct J - 16 oz. Bag', unitPrice: 160.0, quantity: 2, image: 'https://via.placeholder.com/60x60?text=ProductJ' },
      { id: '2', name: 'Brand Name\nProduct K - 16 oz. Bag', unitPrice: 175.0, quantity: 1, image: 'https://via.placeholder.com/60x60?text=ProductK' },
    ],
    tax: 5,
    discount: 5,
    shippingCost: 150.0,
    subTotal: 495.0,
    paymentAmount: 519.75,
    paid: true,
  },
  {
    id: '10240',
    status: 'shipped',
    placedDate: 'Sep 28, 2025',
    trackingNo: '62562622',
    items: [
      { id: '1', name: 'Brand Name\nProduct L - 16 oz. Bag', unitPrice: 85.0, quantity: 2, image: 'https://via.placeholder.com/60x60?text=ProductL' },
    ],
    tax: 5,
    discount: 5,
    shippingCost: 85.0,
    subTotal: 170.0,
    paymentAmount: 178.5,
    paid: true,
  },
];

export default ORDERS_DATA;
