
import type { Metadata } from "next";
import { ReactNode } from "react";
import { Poppins } from "next/font/google";
import "./globals.css";


const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
  <html lang="en" className={poppins.className} suppressHydrationWarning>
   
    <body suppressHydrationWarning>
      <div  className="bg-white text-[#212121]">
          
        
        {children}
        
      </div>

    </body>
  </html>
);
}